import Mathlib

/-! # Smooth-Pasting Inversion (AIRTIGHT Task 1a)

  R1 proved that value+slope match HOLD at the posited boundary S*.
  This file proves the CONVERSE: the smooth-pasting system (value-match AND
  slope-match together) has a UNIQUE solution, and that solution IS
  `S* = Kγ/(γ+1)` (call) / `S* = K(γ+1)/γ` (put) with the R1 coefficients.

  The boundary is not posited-then-checked; it is GENERATED by requiring C¹
  pasting of the exp-family continuation onto the intrinsic.
-/

noncomputable section
open Real

/-! ## R1 Definitions (self-contained copies) -/

/-- Call-wing smooth-pasting boundary. -/
def Sstar_A (K γ : ℝ) : ℝ := K * γ / (γ + 1)

/-- Put-wing smooth-pasting boundary. -/
def Sstar_B (K γ : ℝ) : ℝ := K * (γ + 1) / γ

/-- Call-wing continuation coefficient: `a = (S*_A)^γ / (γ+1)`. -/
def coeffA (K γ : ℝ) : ℝ := (Sstar_A K γ) ^ γ / (γ + 1)

/-- Put-wing continuation coefficient: `b = (S*_B)^(-γ) / (γ+1)`. -/
def coeffB (K γ : ℝ) : ℝ := (Sstar_B K γ) ^ (-γ) / (γ + 1)

/-! ## Bridge lemmas: derivative of `a * x ^ p` via HasDerivAt

  These connect the explicit derivative formula to the `HasDerivAt` API,
  ensuring the `HasDerivAt` formulation is not silently dropped. -/

/-- The derivative of `x ↦ a * x ^ p` at `S > 0` is `p * a * S ^ (p - 1)`.
    This is the general bridge lemma; the call and put cases are special instances. -/
theorem hasDerivAt_const_mul_rpow (a p S : ℝ) (hS : 0 < S) :
    HasDerivAt (fun x => a * x ^ p) (p * a * S ^ (p - 1)) S := by
  have h := (hasDerivAt_rpow_const (p := p) (Or.inl hS.ne')).const_mul a
  convert h using 1; ring

/-- Bridge: the call-wing derivative `-γ * a * S^(-γ-1)` equals the `HasDerivAt`
    content for the continuation `a * x^(-γ)`. -/
theorem hasDerivAt_call (a γ S : ℝ) (hS : 0 < S) :
    HasDerivAt (fun x => a * x ^ (-γ)) (-γ * a * S ^ (-γ - 1)) S := by
  have h := hasDerivAt_const_mul_rpow a (-γ) S hS
  convert h using 1

/-- Bridge: the put-wing derivative `γ * b * S^(γ-1)` equals the `HasDerivAt`
    content for the continuation `b * x^γ`. -/
theorem hasDerivAt_put (b γ S : ℝ) (hS : 0 < S) :
    HasDerivAt (fun x => b * x ^ γ) (γ * b * S ^ (γ - 1)) S :=
  hasDerivAt_const_mul_rpow b γ S hS

/-! ## Auxiliary rpow manipulation lemmas -/

/-- For `S > 0`: from `a * S ^ (-γ) = c`, deduce `a = c * S ^ γ`. -/
private theorem coeff_from_neg_rpow (a c S γ : ℝ) (hS : 0 < S)
    (h : a * S ^ (-γ) = c) : a = c * S ^ γ := by
  rw [← h, mul_assoc, ← rpow_add hS, neg_add_cancel, rpow_zero, mul_one]

/-- For `S > 0`: from `b * S ^ γ = c`, deduce `b = c * S ^ (-γ)`. -/
private theorem coeff_from_rpow (b c S γ : ℝ) (hS : 0 < S)
    (h : b * S ^ γ = c) : b = c * S ^ (-γ) := by
  rw [← h, mul_assoc, ← rpow_add hS, add_neg_cancel, rpow_zero, mul_one]

/-! ## Call wing: slope equation implies product identity -/

/-- From the call-wing slope equation `-γ * a * S^(-γ-1) = -1/K`, derive
    `a * S^(-γ) = S / (γ * K)`.

    Proof: from the slope equation, `a * S^(-γ-1) = 1/(γK)`.
    Then `a * S^(-γ) = a * S^(-γ-1) * S = S/(γK)`,
    using `S^(-γ) = S^(-γ-1) * S` (i.e. `rpow_add`). -/
theorem call_slope_to_product (a γ K S : ℝ) (hS : 0 < S) (hγ : 0 < γ)
    (hs : -γ * a * S ^ (-γ - 1) = -(1 / K)) :
    a * S ^ (-γ) = S / (γ * K) := by
  have key : a * S ^ (-γ) = a * S ^ (-γ - 1) * S := by
    conv_lhs => rw [show (-γ : ℝ) = (-γ - 1) + 1 from by ring]
    rw [rpow_add hS, rpow_one, mul_assoc]
  rw [key]
  have h1 : a * S ^ (-γ - 1) = 1 / (γ * K) := by
    have hγ0 : γ ≠ 0 := ne_of_gt hγ
    have : -γ * (a * S ^ (-γ - 1)) = -(1 / K) := by linarith
    field_simp at this ⊢; linarith
  rw [h1]; ring

/-! ## Call wing: UNIQUENESS -/

/-- **Sstar_A_forced**: the smooth-pasting system for the call wing has a unique
    solution `S = Kγ/(γ+1)`.

    Proof: from `call_slope_to_product`, `a * S^(-γ) = S/(γK)`.
    Equating with the value match `a * S^(-γ) = 1 - S/K`:
      `S/(γK) = 1 - S/K` ⟹ `S(γ+1)/(γK) = 1` ⟹ `S = Kγ/(γ+1)`. -/
theorem Sstar_A_forced (K γ a S : ℝ) (hK : 0 < K) (hγ : 1 < γ) (hS : 0 < S)
    (hv : a * S ^ (-γ) = 1 - S / K)
    (hs : -γ * a * S ^ (-γ - 1) = -(1 / K)) :
    S = Sstar_A K γ := by
  have h_eq := call_slope_to_product a γ K S hS (by linarith) hs
  unfold Sstar_A; rw [h_eq] at hv; field_simp at hv ⊢; nlinarith

/-- **coeffA_forced**: the smooth-pasting system forces `a = coeffA K γ`.

    Proof: by `Sstar_A_forced`, `S = Kγ/(γ+1)`.
    From the value match and `coeff_from_neg_rpow`, `a = (1 - S/K) * S^γ`.
    Substituting `S = Sstar_A K γ`: `1 - S/K = 1/(γ+1)`, so
    `a = S^γ/(γ+1) = (Sstar_A K γ)^γ/(γ+1) = coeffA K γ`. -/
theorem coeffA_forced (K γ a S : ℝ) (hK : 0 < K) (hγ : 1 < γ) (hS : 0 < S)
    (hv : a * S ^ (-γ) = 1 - S / K)
    (hs : -γ * a * S ^ (-γ - 1) = -(1 / K)) :
    a = coeffA K γ := by
  have hS_eq : S = Sstar_A K γ := Sstar_A_forced K γ a S hK hγ hS hv hs
  have ha : a = (1 - S / K) * S ^ γ := coeff_from_neg_rpow a _ S γ hS hv
  have hfrac : 1 - S / K = 1 / (γ + 1) := by
    rw [hS_eq]; unfold Sstar_A; field_simp; ring
  rw [ha, hfrac, hS_eq]; unfold coeffA; ring

/-! ## Put wing: slope equation implies product identity -/

/-- From the put-wing slope equation `γ * b * S^(γ-1) = K/(S*S)`, derive
    `b * S^γ = K / (γ * S)`.

    Proof: from slope, `b * S^(γ-1) = K/(γ · S²)`.
    Then `b * S^γ = b * S^(γ-1) · S = K·S/(γ·S²) = K/(γ·S)`. -/
theorem put_slope_to_product (b γ K S : ℝ) (hS : 0 < S) (hγ : 0 < γ)
    (hs : γ * b * S ^ (γ - 1) = K / (S * S)) :
    b * S ^ γ = K / (γ * S) := by
  have key : b * S ^ γ = b * S ^ (γ - 1) * S := by
    conv_lhs => rw [show (γ : ℝ) = (γ - 1) + 1 from by ring]
    rw [rpow_add hS, rpow_one, mul_assoc]
  rw [key]
  have hbSγ : b * S ^ (γ - 1) = K / (γ * (S * S)) := by
    have hγ0 : (γ : ℝ) ≠ 0 := ne_of_gt hγ
    have hSS : S * S ≠ 0 := mul_ne_zero hS.ne' hS.ne'
    have h1 : γ * (b * S ^ (γ - 1)) = K / (S * S) := by linarith
    rw [eq_div_iff hSS] at h1
    rw [eq_div_iff (mul_ne_zero hγ0 hSS)]
    linarith
  rw [hbSγ]; field_simp

/-! ## Put wing: UNIQUENESS -/

/-- **Sstar_B_forced**: the smooth-pasting system for the put wing has a unique
    solution `S = K(γ+1)/γ`.

    Proof: from `put_slope_to_product`, `b * S^γ = K/(γS)`.
    Equating with value match `b * S^γ = 1 - K/S`:
      `K/(γS) = 1 - K/S` ⟹ `K(γ+1)/(γS) = 1` ⟹ `S = K(γ+1)/γ`. -/
theorem Sstar_B_forced (K γ b S : ℝ) (_hK : 0 < K) (hγ : 1 < γ) (hS : 0 < S)
    (hv : b * S ^ γ = 1 - K / S)
    (hs : γ * b * S ^ (γ - 1) = K / (S * S)) :
    S = Sstar_B K γ := by
  have h_eq := put_slope_to_product b γ K S hS (by linarith) hs
  unfold Sstar_B; rw [h_eq] at hv; field_simp at hv ⊢; nlinarith

/-- **coeffB_forced**: the smooth-pasting system forces `b = coeffB K γ`.

    Proof: by `Sstar_B_forced`, `S = K(γ+1)/γ`.
    From the value match and `coeff_from_rpow`, `b = (1 - K/S) * S^(-γ)`.
    Substituting `S = Sstar_B K γ`: `1 - K/S = 1/(γ+1)`, so
    `b = S^(-γ)/(γ+1) = (Sstar_B K γ)^(-γ)/(γ+1) = coeffB K γ`. -/
theorem coeffB_forced (K γ b S : ℝ) (hK : 0 < K) (hγ : 1 < γ) (hS : 0 < S)
    (hv : b * S ^ γ = 1 - K / S)
    (hs : γ * b * S ^ (γ - 1) = K / (S * S)) :
    b = coeffB K γ := by
  have hS_eq : S = Sstar_B K γ := Sstar_B_forced K γ b S hK hγ hS hv hs
  have hb : b = (1 - K / S) * S ^ (-γ) := coeff_from_rpow b _ S γ hS hv
  have hfrac : 1 - K / S = 1 / (γ + 1) := by
    rw [hS_eq]; unfold Sstar_B; field_simp; ring
  rw [hb, hfrac, hS_eq]; unfold coeffB; ring

/-! ## Axiom audit -/

#print axioms hasDerivAt_const_mul_rpow
#print axioms hasDerivAt_call
#print axioms hasDerivAt_put
#print axioms Sstar_A_forced
#print axioms coeffA_forced
#print axioms Sstar_B_forced
#print axioms coeffB_forced

end
