export const chains = [
  {
    name: "tUSD",
    icon: "./logo_tUSD.svg",
    token: "tUSD",
    crossToken:"tUSD - tEUR",
    logoSrc: "./logo_tUSD.svg",
    gradientColor: "50, 175, 149",
    tokenYield: "4.4%",
    api: "https://tUSD.temporal.exchange",
    crossCurrencyApi:"https://tUSDtEUR.temporal.exchange",
    backendString: "3",
    crossCurrencyBackendString: "1"
  },
  {
    name: "tEUR",
    icon: "./logo_tEUR.svg",
    token: "tEUR",
    crossToken:"tEUR - tUSD",
    logoSrc: "./logo_tEUR.svg",
    gradientColor: "50, 175, 149",
    tokenYield: "4.4%",
    api: "https://tEUR.temporal.exchange",
    crossCurrencyApi:"https://tEURtUSD.temporal.exchange",
    backendString: "4",
    crossCurrencyBackendString: "2"
  },
  // {
  //   name: "tUSD - tEUR",
  //   icon: "./logo_tUSD.svg",
  //   token: "tUSD - tEUR",
  //   logoSrc: "./logo_tUSD.svg",
  //   gradientColor: "41, 49, 125",
  //   tokenYield: "4.4%",
  //   api: "https://pool4.temporal.exchange",
  // },
  // {
  //   name: "tEUR - tUSD",
  //   icon: "./logo_tEUR.svg",
  //   token: "tEUR - tUSD",
  //   logoSrc: "./logo_tEUR.svg",
  //   gradientColor: "41, 49, 125",
  //   tokenYield: "4.4%",
  //   api: "https://pool5.temporal.exchange",
  // },
  // {
  //   name: "sSOL",
  //   icon: "./logo_sol.svg",
  //   token: "sSOL",
  //   logoSrc: "./logo_sol.svg",
  //   gradientColor: "0, 71, 71",
  //   tokenYield: "9.4%",
  // },
  // {
  //   name: "tSOFR",
  //   icon: "./logo_sofr.svg",
  //   token: "tSOFR",
  //   logoSrc: "./logo_sofr.svg",
  //   gradientColor: "0, 81, 18",
  //   tokenYield: "4.4%",
  // },
  // {
  //   name: "stATOM",
  //   icon: "./logo_atom.svg",
  //   token: "ATOM",
  //   logoSrc: "./logo_atom.svg",
  //   gradientColor: "41, 49, 125",
  //   tokenYield: "4.73%",
  // },
  // {
  //   name: "stOSMO",
  //   icon: "./logo_osmo.svg",
  //   token: "OSMO",
  //   logoSrc: "./logo_osmo.svg",
  //   gradientColor: "87, 37, 70",
  //   tokenYield: "7.35%",
  // },
  // {
  //   name: "stETH",
  //   icon: "./logo_stEth.svg",
  //   token: "ETH",
  //   logoSrc: "./logo_stEth.svg",
  //   gradientColor: "61, 61, 61",
  //   tokenYield: "4.56%",
  // },
  // {
  //   name: "stUSDT",
  //   icon: "./logo_usdt.svg",
  //   token: "USDT",
  //   logoSrc: "./logo_usdt.svg",
  //   gradientColor: "50, 175, 149",
  //   tokenYield: "3.72%",
  // },
  //   {
  //     name: "stMATIC",
  //     icon: "./logo_matic.svg",
  //     token: "MATIC",
  //     logoSrc: "./logo_matic.svg",
  //     gradientColor: "120, 43, 199",
  //     tokenYield: "6.84%",
  //   },
];

export const portfolioChains = [
  {
    name: "tUSD",
    icon: "./logo_tUSD.svg",
    token: "tUSD",
    logoSrc: "./logo_tUSD.svg",
    gradientColor: "50, 175, 149",
  },
  {
    name: "tEUR",
    icon: "./logo_tEUR.svg",
    token: "tEUR",
    logoSrc: "./logo_tEUR.svg",
    gradientColor: "50, 175, 149",
  },
  {
    name: "tUSD - tEUR",
    icon: "./logo_tUSD_tEUR.svg",
    token: "tUSD - tEUR",
    logoSrc: "./logo_tUSD_tEUR.svg",
    gradientColor: "41, 49, 125",
  },
  {
    name: "tEUR - tUSD",
    icon: "./logo_tEUR_tUSD.svg",
    token: "tEUR - tUSD",
    logoSrc: "./logo_tEUR_tUSD.svg",
    gradientColor: "41, 49, 125",
  },
];